const iconsPack = {
    star: '/icons/star.png',
    waves: '/icons/waves.png',
    bell: '/icons/bell.png',
    spa: '/icons/spa.png',
    beach: '/icons/beach.png',
    bar: '/icons/bar.png',
    pets: '/icons/pets.png',
    date: '/icons/date.png',
    person: '/icons/person.png',
    knife_spoon: '/icons/knife-spoon.png',
    jakuzi: '/icons/jakuzi.png',
    discount: '/icons/discount.png',
    snow: '/icons/snow.png',
    check: '/icons/check.png',
    redX: '/icons/red_x.png',
    persons: '/icons/persons.png',
    dateThin: '/icons/date_thin.png',
    like: '/icons/like.png',
    location: '/icons/location.png',
    airplane: '/icons/airplane.png',
    discountBlue: '/icons/discount_blue.png',
    lifebuoy: '/icons/lifebuoy.png',
    questionMark: '/icons/question_mark.png',
    locationOutline: '/icons/location-outline.png',
    businessOutline:'/icons/business-outline.png',
    personOutline:'/icons/person_outline.png',
    group:'/icons/group.png',
    family:'/icons/family.png',
    heart:'/icons/heart.png',
};
export default iconsPack; 